window.DOME_MODULES = [
 {n:'01',name:'GEGRAPTAI™',fn:'Scripture & Daily Kingdom Briefing',origin:'Greek · γέγραπται · gegraptai · “It is written”',scripture:'Matthew 4:4',purpose:'Ground the day in the written Word and present Scripture-grounded Kingdom briefing content.',href:'../gegraptai/'},
 {n:'02',name:'NESHAMAH™',fn:'Inspiration / Dynamic Daily Prophetic Word',origin:'Hebrew · נְשָׁמָה · neshamah · “breath”',scripture:'Job 32:8',purpose:'Preserve the governed daily inspirational and prophetic-word function and its history.',href:'../neshamah/'},
 {n:'03',name:'TETELESTAI™',fn:'Completion / Mission Execution',origin:'Greek · τετέλεσται · tetelestai · “It is finished / completed”',scripture:'John 17:4',purpose:'Own projects, tasks, accountability, milestones, priorities, progress, and faithful completion.',href:'../tetelestai/'},
 {n:'04',name:'OrEl™',fn:'Creation, Authoring & Publishing Development',origin:'Dominion1st coined name · Or (light) + El (God)',scripture:'Genesis 1:3',purpose:'Create and develop teachings, manuscripts, research, editing, design, and publication preparation.',href:'../orel/'},
 {n:'05',name:'YARATHĒKĒ™',fn:'Wells of Knowledge / Library & Reader',origin:'Dominion1st coined Knowledge Library identity',scripture:'Isaiah 12:3',purpose:'Preserve and present established knowledge for discovery, reading, study, organization, and retrieval.',href:'../yaratheke/'},
 {n:'06',name:'GRĒGOREŌ™',fn:'Watch / Peace & Safety Intelligence',origin:'Greek · γρηγορέω · grēgoreō · “watch / stay awake / be vigilant”',scripture:'1 Thessalonians 5:3–6',purpose:'Watch conditions and developments requiring vigilance, discernment, prayer, preparation, and responsible response.',href:'../gregoreo/'},
 {n:'07',name:'OIKONOMOS™',fn:'Stewardship & Administration',origin:'Greek · οἰκονόμος · oikonomos · “steward / household manager”',scripture:'Luke 12:42',purpose:'Steward entrusted resources, obligations, finances, assets, property, records, contracts, estate, and legacy.',href:'../oikonomos/'},
 {n:'08',name:'EKKLĒSIA™',fn:'Church / Assembly / The People of God',origin:'Greek · ἐκκλησία · ekklēsia · “assembly / congregation”',scripture:'Matthew 16:18',purpose:'Serve churches, ministries, leaders, teams, partners, families, discipleship, and Kingdom relationships.',href:'../ekklesia/'}
];