import { createClient } from 'npm:@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})
const racMatrix:any={I:{A:1,B:1,C:2,D:4},II:{A:1,B:2,C:3,D:4},III:{A:2,B:3,C:4,D:5},IV:{A:4,B:4,C:5,D:5}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405)
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401)
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const token=auth.replace('Bearer ','');const {data:{user},error:ue}=await userClient.auth.getUser(token);if(ue||!user)return json({error:'Invalid user'},401)
 const admin=createClient(url,service);const body=await req.json();const {action,record_type,record_id}=body;if(!['project','task'].includes(record_type))return json({error:'Invalid record type'},400);const table=record_type==='project'?'projects':'tasks',idcol=record_type==='project'?'project_id':'task_id';const {data:row,error:re}=await admin.from(table).select('*').eq('id',record_id).single();if(re||!row)return json({error:'Record not found'},404);const actor=user.email||user.id
 if(action==='follow_up'){if(!body.action_taken?.trim()||!body.results?.trim())return json({error:'Action taken and results required'},400);const entry:any={record_type,[idcol]:record_id,follow_up_date:body.follow_up_date||new Date().toISOString().slice(0,10),action_taken:body.action_taken.trim(),results:body.results.trim(),next_action:body.next_action||null,next_follow_up_date:body.next_follow_up_date||null,progress_percent:body.progress_percent??null,entered_by:actor};const {data,error}=await admin.from('tetelestai_follow_up_history').insert(entry).select().single();if(error)return json({error:error.message},400);const patch:any={last_follow_up_date:entry.follow_up_date,updated_at:new Date().toISOString()};if(entry.next_follow_up_date)patch.next_follow_up_date=entry.next_follow_up_date;if(entry.next_action)patch.next_action=entry.next_action;if(entry.progress_percent!==null)patch.percent_complete=entry.progress_percent;await admin.from(table).update(patch).eq('id',record_id);return json({ok:true,entry})}
 if(action==='update_current'){const allowed=['status','priority','action_owner','readiness','next_action','next_follow_up_date','follow_up_interval_days','percent_complete','description','notes','priority_method','apn_cost','apn_exposure'];const changes:any={};for(const k of allowed){if(body.fields&&Object.prototype.hasOwnProperty.call(body.fields,k)&&String(body.fields[k]??'')!==String(row[k]??'')){if(k==='priority_method'&&!['epi','apn'].includes(String(body.fields[k])))return json({error:'Priority method must be epi or apn'},400);if(k==='apn_cost'&&body.fields[k]!==null&&(!Number.isFinite(Number(body.fields[k]))||Number(body.fields[k])<0))return json({error:'APN cost must be zero or greater'},400);if(k==='apn_exposure'&&body.fields[k]!==null&&(!Number.isFinite(Number(body.fields[k]))||Number(body.fields[k])<=0))return json({error:'APN exposure must be greater than zero'},400);changes[k]=body.fields[k];await admin.from('tetelestai_change_history').insert({record_type,[idcol]:record_id,field_name:k,old_value:String(row[k]??''),new_value:String(body.fields[k]??''),reason:body.reason||null,changed_by:actor})}}if(!Object.keys(changes).length)return json({ok:true,changed:0});changes.updated_at=new Date().toISOString();const {error}=await admin.from(table).update(changes).eq('id',record_id);if(error)return json({error:error.message},400);return json({ok:true,changed:Object.keys(changes).length})}
 if(action==='user_rac'){const s=body.severity,p=body.probability,rac=racMatrix[s]?.[p];if(!rac)return json({error:'Invalid RAC inputs'},400);const {data,error}=await admin.from('dea_risk_assessments').insert({record_type,[idcol]:record_id,assessment_type:'user',severity:s,probability:p,rac,rationale:body.rationale||null,assessed_by:actor}).select().single();if(error)return json({error:error.message},400);return json({ok:true,assessment:data,system_rac:row.system_rac})}
 if(action==='challenge_rac'){const s=body.severity,p=body.probability,rac=racMatrix[s]?.[p];if(!rac||!body.rationale?.trim())return json({error:'RAC and rationale required'},400);const {data,error}=await admin.from('dea_risk_assessments').insert({record_type,[idcol]:record_id,assessment_type:'challenge',severity:s,probability:p,rac,rationale:body.rationale.trim(),assessed_by:actor,review_status:'pending'}).select().single();if(error)return json({error:error.message},400);return json({ok:true,challenge:data,system_rac:row.system_rac})}
 return json({error:'Unknown action'},400)
})