const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let step=1,currentSubject='VISION';
function show(n){step=n;$$('.stage').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));$$('[data-go]').forEach(x=>x.classList.toggle('on',+x.dataset.go===n));$('#experience').scrollIntoView({behavior:'smooth',block:'center'});}
$$('[data-go]').forEach(b=>b.onclick=()=>show(+b.dataset.go));
function render(subject){
 const key=subject.trim().toUpperCase(), x=window.D1_EXPERIENCES[key];
 if(!x){$('#subjectSub').textContent='This subject is ready for live AI generation. The prototype currently includes VISION, FAITH, and DOMINION.';return false}
 currentSubject=key;document.body.dataset.scene=x.scene;$('#subjectTitle').textContent=key;$('#subjectInput').value=key;$('#subjectSub').textContent=x.subtitle;
 $('#scriptureText').textContent='“'+x.scripture.text+'”';$('#scriptureRef').textContent=x.scripture.ref;$('#scriptureThought').textContent=x.scripture.thought;
 $('#seeLead').textContent=x.see.lead;$('#vistaOverline').textContent=x.see.overline;$('#vistaTitle').textContent=x.see.title;$('#seeBody').textContent=x.see.body;
 $('#mindsetLead').textContent=x.mindset.lead;$('#mindsetBody').textContent=x.mindset.body;
 $('#declarationText').innerHTML=x.declaration.map((v,i)=>i===x.declaration.length-1?'<strong>'+v+'</strong>':v).join('<br>');
 $('#doitLead').textContent=x.doit.lead;$('#doitBody').textContent=x.doit.body;refresh();applyScene(x);return true;
}
async function generateExperience(){const subject=$('#subjectInput').value.trim().toUpperCase();if(render(subject)){show(1);return}const btn=$('#generateBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='GENERATING…';$('#subjectTitle').textContent=subject||'WORD';$('#subjectSub').textContent='Seeking a Scripture-centered experience…';try{const res=await fetch('/api/experience',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject,mode:mode.value,day:1,duration:+dur.value||1})});const out=await res.json();if(!res.ok||!out.experience)throw new Error(out.message||out.error||'Live generation is not connected yet.');window.D1_EXPERIENCES[subject]=out.experience;render(subject);show(1)}catch(err){$('#subjectSub').textContent=err.message+' Try VISION, FAITH, or DOMINION in this prototype.'}finally{btn.disabled=false;btn.textContent=old}}async function applyScene(x){const layer=$('#generatedScene'),state=$('#sceneState');layer.style.backgroundImage='';state.textContent='SCENE: ATMOSPHERIC';if(!x.scenePrompt)return;state.textContent='SCENE: GENERATING…';try{const res=await fetch('/api/scene',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject:currentSubject,scriptureRef:x.scripture.ref,scenePrompt:x.scenePrompt})});const out=await res.json();if(!res.ok||!out.imageUrl)throw new Error();layer.style.backgroundImage='url("'+out.imageUrl.replace(/"/g,'')+'")';state.textContent='SCENE: AI DYNAMIC'}catch(e){state.textContent='SCENE: ATMOSPHERIC'}}
$('#generateBtn').onclick=generateExperience;
$('#subjectInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#generateBtn').click()});
const mode=$('#mode'),dur=$('#duration'),date=$('#targetDate'),status=$('#journeyStatus');
function modeUI(){const m=mode.value;$('#durationWrap').hidden=m!=='journey';$('#dateWrap').hidden=m!=='countdown';status.hidden=m==='theme';refresh();}
function refresh(){if(mode.value==='journey')status.textContent='A '+dur.value+'-DAY '+currentSubject+' JOURNEY';if(mode.value==='countdown'){if(!date.value){status.textContent='SELECT THE APPOINTED DATE';return}const d=Math.ceil((new Date(date.value+'T23:59:59')-new Date())/86400000);status.textContent=d>0?d+' DAYS UNTIL THE APPOINTED TIME':d===0?'THE APPOINTED DAY IS HERE':'THE APPOINTED DATE HAS PASSED';}}
mode.onchange=modeUI;dur.oninput=refresh;date.onchange=refresh;modeUI();render('VISION');
$('#beginBtn').onclick=()=>show(1);
$('#declareBtn').onclick=e=>{e.currentTarget.textContent='DECLARED ✓';setTimeout(()=>show(5),650)};
$('#completeBtn').onclick=()=>{const key='d1-biblical-'+currentSubject.toLowerCase()+'-progress',saved=JSON.parse(localStorage.getItem(key)||'{}');saved.completed=(saved.completed||0)+1;saved.last=new Date().toISOString();saved.see=$('#seeInput').value;saved.action=$('#doInput').value;localStorage.setItem(key,JSON.stringify(saved));if(mode.value==='journey'&&saved.completed>=+dur.value){$('#teleiosSubject').textContent=currentSubject+' — a memorial of Word received, truth seen, declaration spoken, and action taken.';$('#teleiosJourney').textContent=dur.value+' DAYS • '+currentSubject;$('#teleiosDate').textContent=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});$('#teleios').hidden=false;$('#teleios').scrollIntoView({behavior:'smooth'});}else $('#completeBtn').textContent='TODAY ESTABLISHED ✓';};
$('#soundBtn').onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.textContent='SOUND: '+(on?'READY':'OFF');};
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&step<5)show(step+1);if(e.key==='ArrowLeft'&&step>1)show(step-1)});