// Spartans1st browser data client. Publishable key only; RLS is the authorization boundary.
const S1_URL='https://sdquzhsylqpbhrmqjqgk.supabase.co',S1_KEY='sb_publishable_volaz6N52Pc4rdh8a4dfEw_MjJ73How';
async function s1(path,options={}){const token=localStorage.getItem('spartans1st_access_token');const headers={apikey:S1_KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(options.headers||{})};const r=await fetch(S1_URL+'/rest/v1/'+path,{...options,headers});if(!r.ok)throw new Error('S1 data '+r.status);const t=await r.text();return t?JSON.parse(t):null}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
async function s1LoadAthleteHome(){if(localStorage.getItem('spartans1st_demo_mode')==='1'){window.s1Demo=true;document.documentElement.dataset.s1Data='demo';document.querySelector('.hero h1').textContent='Today · Test Athlete';document.querySelector('.mark span').textContent='Test MARK — demonstrate disciplined daily progress toward a measurable season goal.';const w=document.querySelectorAll('#word .word small');w[0].textContent='Test LOGOS — governing truth / standard';w[1].textContent='Test RHEMA — apply today’s standard to today’s work';w[2].textContent='Test DECLARATION — I will train with purpose, fight through challenge, and press toward the mark.';document.querySelector('#doit p').innerHTML='<b>Coach-assigned workout:</b> Test progression run — fictional sample assignment for functional testing.';return}if(!localStorage.getItem('spartans1st_access_token')){document.documentElement.dataset.s1Data='awaiting-auth';return}try{const aa=await s1('spartans1st_athletes?select=id,display_name&limit=1');if(!aa?.length){document.documentElement.dataset.s1Data='no-athlete-profile';return}const a=aa[0],today=new Date().toISOString().slice(0,10);const [m,w,r,t]=await Promise.all([s1('spartans1st_marks?select=mark&athlete_id=eq.'+a.id+'&status=eq.active&order=updated_at.desc&limit=1'),s1('spartans1st_daily_content?select=logos,rhema,declaration&content_date=eq.'+today+'&audience=eq.athlete&limit=1'),s1('spartans1st_readiness?select=status,note&athlete_id=eq.'+a.id+'&readiness_date=eq.'+today+'&limit=1'),s1('spartans1st_training_assignments?select=id,title,instructions,status&athlete_id=eq.'+a.id+'&training_date=eq.'+today+'&limit=1')]);document.querySelector('.hero h1').textContent='Today · '+a.display_name;if(m?.[0])document.querySelector('.mark span').textContent=m[0].mark;if(w?.[0]){const z=document.querySelectorAll('#word .word small');z[0].textContent=w[0].logos||'—';z[1].textContent=w[0].rhema||'—';z[2].textContent=w[0].declaration||'—'}if(r?.[0]){const q=document.getElementById('readinessSelect');if(q){q.value=r[0].status||'';readinessChanged(q.value)}const n=document.getElementById('readinessNote');if(n)n.value=r[0].note||'';}if(t?.[0]){document.querySelector('#doit p').innerHTML='<b>Coach-assigned workout:</b> '+esc(t[0].title)+(t[0].instructions?' — '+esc(t[0].instructions):'');window.s1TrainingId=t[0].id}window.s1AthleteId=a.id;document.documentElement.dataset.s1Data='connected'}catch(e){document.documentElement.dataset.s1Data='error';console.error(e)}}
async function s1SaveReadiness(status,note=''){if(window.s1Demo){localStorage.setItem('spartans1st_demo_readiness',status);localStorage.setItem('s1_demo_readiness_note',note);return say('Test readiness saved locally: '+status)}if(!window.s1AthleteId)return say('Sign-in/profile connection required before saving.');const today=new Date().toISOString().slice(0,10);try{await s1('spartans1st_readiness?on_conflict=athlete_id,readiness_date',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({athlete_id:window.s1AthleteId,readiness_date:today,status,note:note||null})});say('Readiness saved.')}catch(e){say('Readiness was not saved.')}}
window.addEventListener('DOMContentLoaded',s1LoadAthleteHome);
async function s1CompleteTraining(){
 if(window.s1Demo||!window.s1TrainingId)return true;
 try{await s1('spartans1st_training_assignments?id=eq.'+window.s1TrainingId,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'completed',completed_at:new Date().toISOString()})});return true}catch(e){say('Training completion was not saved.');return false}
}
async function s1SaveResult(data){
 if(window.s1Demo){localStorage.setItem('s1_demo_result',JSON.stringify(data));return {id:'demo-result'}}
 if(!window.s1AthleteId)return say('Sign-in/profile connection required before saving.');
 try{const rows=await s1('spartans1st_results',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({athlete_id:window.s1AthleteId,training_assignment_id:window.s1TrainingId||null,result_date:new Date().toISOString().slice(0,10),result_text:JSON.stringify(data),is_pr:!!data.is_pr,prize:data.prize||null})});window.s1ResultId=rows?.[0]?.id||null;return rows?.[0]||null}catch(e){say('Result was not saved.');return null}
}
async function s1SaveReview(data){
 if(window.s1Demo){localStorage.setItem('s1_demo_review',JSON.stringify(data));return true}
 if(!window.s1AthleteId)return say('Sign-in/profile connection required before saving.');
 try{await s1('spartans1st_reviews',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({athlete_id:window.s1AthleteId,result_id:window.s1ResultId||null,integrity:data.integrity||null,effectiveness:data.effectiveness||null,efficiency:data.efficiency||null,excellence:data.excellence||null,improve_next:data.improve||null})});return true}catch(e){say('Review was not saved.');return false}
}
